name: ape_match
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.4
  firebase_core:  ^1.10.5
  firebase_auth: ^3.3.3
  flutter_riverpod: ^1.0.2
  google_fonts: ^2.1.0
  cached_network_image: ^3.2.0
  freezed_annotation: ^1.0.0
  json_annotation: ^4.4.0
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.3
  bubble: ^1.2.1
  keyboard_actions: ^3.4.5
  webview_flutter: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  freezed: ^1.0.2
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "images/appIcon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/apeIcon.png
    - images/noImage.png
    - images/mypageBack.png
    - images/ranks_images/bronze.png
    - images/ranks_images/gold.png
    - images/ranks_images/master.png
    - images/ranks_images/platinum.png
    - images/ranks_images/predator.png
    - images/ranks_images/silver.png
    - images/ranks_images/diamond.png

